### ISSUE TITLE
Unable to connect to zookeeper

### ISSUE THREAD

**Issue by atfire** [kakao/hbase-region-inspector#3]
I'm trying to run hbase-region-inspector like this:
`./hbase-region-inspector-0.3.7-cdh4 ~/Desktop/hri.properties 7777`

And my properties file looks like this:
```
hbase.zookeeper.quorum=<myhostname>
hbase.zookeeper.property.clientPort=2181
```

I always see an error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Not a host:port pair: PBUF
/
"<myhostname>�������+��
	at org.apache.hadoop.hbase.util.Addressing.parseHostname(Addressing.java:60)
	at org.apache.hadoop.hbase.ServerName.<init>(ServerName.java:101)
	at org.apache.hadoop.hbase.ServerName.parseVersionedServerName(ServerName.java:283)
	at org.apache.hadoop.hbase.MasterAddressTracker.bytesToServerName(MasterAddressTracker.java:77)
	at org.apache.hadoop.hbase.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:61)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:805)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:129)
	at hbase_region_inspector.hbase$connect_admin.invokeStatic(hbase.clj:117)
	at hbase_region_inspector.hbase$connect_admin.invoke(hbase.clj:112)
	at hbase_region_inspector.core$collect_info.invokeStatic(core.clj:139)
	at hbase_region_inspector.core$update_regions_BANG_$fn__4536.invoke(core.clj:320)
	at hbase_region_inspector.core$update_regions_BANG_.invokeStatic(core.clj:320)
	at hbase_region_inspector.core$bootstrap.invokeStatic(core.clj:483)
	at hbase_region_inspector.core$_main.invokeStatic(core.clj:530)
	at hbase_region_inspector.core$_main.doInvoke(core.clj:516)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at hbase_region_inspector.core.main(Unknown Source)

```

I also tried several ways to run providing a quorum/port via command line args, but result was the same.

Am I doing something wrong?

**Comment by junegunn** [comment]
Seems like you're not using the right binary for your HBase cluster. Which version of HBase are you running? Please see if [the binary without `-cdh4` suffix](https://github.com/kakao/hbase-region-inspector/releases/download/v0.3.7/hbase-region-inspector-0.3.7) works for you.

**Comment by atfire** [comment]
You are right, everything works with the other binary. Thanks!
